language: python
python:
- '3.4'
branches:
  only:
  - horizon
  - master
env:
  global:
  - GH_REF: github.com/brownplt/pyret-docs.git
  - RACKET_DIR: ~/racket
  - RACKET_VERSION: '6.5'
  - secure: hjhNWqtc4sfQMfhrOLH8ugrWQu+f26AUOoyfuFkRhAVv/P0464yLNyV1rPgQ0Z15uEFKvpZ4leCIhNEwpDC+3yF8E8LPK8/UEPbI8gofFt52LOAZgHErTKgw2T+MspmLprslaRzfeyJcPgX1u4ocZbcAjFnalnarcLcDq2LdvB3yhIlhef8PI3QzqP0Tzfpl06F3/aIcfayoHyxMzN5pL7dem6OZ/Y2BLGrxP/wX75t9IIMBuK9q9c7/J21erLlDQHpl7B7QDKOabj6VNBG6Fvved4u/7VMFQ1giFlYmcZPkK2iDlRkF2R3UO8v13yhEBvYpSjYDPPAn6GUp/Jd1VmuHSTBWCxt00tg1Tv6iXjaEiFy0NHJqoV8Ykpj+xSEyePEuqLAqwHOiSygGTUPPh6fT1dvhaq2lvtKuEJMIgcQ3VxREjcVve7AlVxfqMtcmg6f7ostnUde3jp3TuaDt7bkNx6rYm3yRzPxA3BHg+OIfvUVg5emul0qrbGsag4rDq1U2/ehN8v0WG3VBnbbCl66wszvSTrcda4GV1De2J4kldtgb5SCI9h5rQPzUut2FE68AmEJpQ69a6O6DKzTFOL7Xo35FTIjB9kIQ0i4cY6ywE5kGCAQeN/lwS1+X3BMujdG3y4JfsZ3prrO4vJzoXQdlikIab4Q88KC2hH2LsDI=
  - secure: d24klpZN/vRHJkYMyZkUtXht6oYfOekfRyNtijA9bIJqUxX7hCaDZPnHxpSY+vR+lPEuJv7C3KO+fdfUNGT6BbT/V7laj5Q6R0vWPO3cSOkGSr4QbnjpkJD+dVmCg5sv0/NtMybsfxCoxJzQrXsKGF6EXQX0s5b+kZ3UTCHbJGbxblDzarpdIIJWOxct2gPGOrkybstF8+xwhIqt7uM/bnt6ZYvbly4AayABEnNumjP3uQNOnuhETuqYoPo80HR5H5vXETGc6y22Oqt9A4Y4M6KSrDRg0bFPTci3n3osE2/x5GNB9xLzj0C32g91v26XXt0WEzHDPcGY81r56rlGL/s+Q9Rr1JH/Qx3D6GOV8lqNOVBB/Jtt1R7B6JKOASM0of/qxJnIApU+SdIaEZidpstdBrLRILp9lyUIRAhwciQKILyyYPbkNdoWPnMXdX81vk4786XhT7L9cv/RQunvXKyynmVrJlVhGC6cCsTpiLSl8MeaVEknsFgrCfAoTMzrUagD9urL3oD18nWEKrqidbywSLN1dXZ7WNavMFjDMDk/iOO9NJRV2sezGn/jx69vT5EHGNunsj2SNZl0vcUGbo7bMaKfE+IeF1NSybPSC3vMzHLDrcqoqpNMi/dCS84Roe+JcLFIybEB2y7RHvWfJHXHHAssSVz42z+jxlO3SHo=
before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash
- export PATH="${RACKET_DIR}/bin:${PATH}"
script: bash ./deploy.sh
