language: python
python:
- '3.4'
branches:
  only:
  - horizon
  - master
env:
  global:
  - GH_REF: github.com/brownplt/pyret-docs.git
  - RACKET_DIR: "~/racket"
  - RACKET_VERSION: '6.5'
  - secure: tkOgKmY5brk6wSTluhgKaFiUiVVXnf1HefE1v56LOUlNHcieMLjRAgXc5LsdezI5ymtf59tZBVAdv7zWG+2Co/nMgIVE20FLpT2UeZCyBu+669lDPZG5zJcsq3Yp52EyE3pSzBRc5H5c9Ni3AZWunV/OxV8xUn3TMkTz9ian/j1AiyDK6z/s5TyFVuRITUOriyuE84e5HJvSYdCjMH2jZE3vCp+lBO9xK/+7IAyoXM7LBFIxz2qBbfzeGbDUzMiFujJZ0/cJu8Qfjlz/AEzW13BWhzhrI9FWUaawKJX1xU6gv9uhRgmsQqQjOMe2CdDuUiUoFP11WjbSnSsN7/B3oklqSiHNHFnOCbxYqunpEpI4EOltL0SpEFHZYl5JgtsLJTbqZvAJ0AaT88F8HBJEFthxyz6MhbBZ9CewOpFY50qY7yvsLr6JEEzCEnTk2EtIv6r2Ux5Xad+K2AXfpEPR1VvfRl6J4U7JGKHHspNVJmpdZSnJdYTzS2siHknV4LQ5Zrl1uwhTjTc4H6bshDKQfcXFkkc4edV78jrJiPDP5hpPVaqLH5MTLV0mhsrSowHPaOyL6y3y+/mrUFG7F0Lha9qdtT4k8PvD47ldPxBCaFOh85MC+w+p65WFqf2rwFMmZNA9sUTltFvU5OMtBPfTMpCrhgnBhf62UrLm6z2jJZY=
  - secure: LNFPDErTqBbgv3XgDI+X9q9Clb/BCFeuUcHjpzP5w5u4y2hpe3TnOkrLfI/FNNYqL2wczqA9cyQ6tDsczFatxz936heSU087uimPCEHKYuUk4jCZ3vM1iIH+MeiAEnaSDXmHOS0iSxvX86BU5AYULlRdpCNqU/12dzJZdARYhIGX+7LNUCUf2/D9MAbL85OjGjzR6ZEaJ5TdvL7IPKejsABiyU/TEAD6PNIgPaL4MRv+gqhedOak7nhFHUfJFUOVQ/GFE9np46HWW19aGIJSktO7RRCsDESUBte19qdQz+pABgn/mR3zVYsn0x7bd9VhpGHt5yeEpAhm82GB5MdkLVYCap8SgGHzl6IAXyToBTmC6wDxOQ/ivpWnkDum1W2rEuY/HrT1235Z7ea5YZVajg5uxAcnkpYqkOyWrLMm7yjXY6wdNQ9F1YKyx6GOxpZj/5opib3aF0hxIRF5nHD2ROZVgLeBM6PKliES1/X5GutBQCh3PsXwGd1G40YtUPXghMwxjYiDmwkM05fOnrUqwfobz98yrDm/6Q7KUEqUaUcV/RshLYcgXrOgSv9YSDykJ7BkvFhnDTOiHPVc4gg4GFHjZI0T8cCziyeroo3/pfR/Oe1kIXyuCzpP4kbY48JGE7GEvC7vT/dwOQ4ERt4XfzD2jlBaubqI6Boy95+VrKo=
before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash
- export PATH="${RACKET_DIR}/bin:${PATH}"
deploy:
  provider: s3
  bucket: pyret-docs
  local_dir: build
  upload-dir: docs/horizon
  skip_cleanup: true
  secret_access_key:
    secure: dpOgfMt7X6Q/m5wvHqMLT0ytSAAPQbXXhrGY3hTAlvUAYsXN2NUCbj6UBLvtJPTUtNbpnlSywJZ8PhH44GAJwTGJbIgT3kgOjGO5stwdVChYuIgoOTXvksHe0zx2KKJ6qozKGuNiq0UFNdS5peF0vXah7MRsxvvZRvI9LvO0RPdM1x92FP2YOdJYxlw17pKM/jTDpIPDWbNe8mtFM1SvdZrRGnrHxYjHSHJwj6C1Lnn+myrIX5/QDmv/QrwWt0/BL0oXKIwgmTdW4LYKaVD1gFcSHAplDPI1kCzJotjsChPw/d6/mSU6fL0yMWJxwofdZTbi2aYqbviVOhXIqOKIw6aBMgxHnGoGI/THsF8hQkMLRJFdw+9/sThy/Z5iWBHLaZp1rur9CcQTLVQXBZ6AMbhnNqDnPbTm9eGidoyi48sAZPX/8zIqbvFAvA7M1mrrMJwSmaE/U1nGi+XgcDx0pDSuW130hQOzzQJzyS4WdACRbGmpQbnfv3ikeap6QaSLnTmqfTOyTDUWXj23SP3eW/VWeIXMAeK1oTHR+Lk8U9A0C9FC1j17qm02LwtdpgbzvGlAKZ6QNdMcgalBYj2daCw2T8TEUZ4QX5FdYX40tatcM7gYP8BJ/9IJq+uRrwU+hzXQLpjsXLlW/cv5yWHiFOa61jL96l8F8xgYufm0Il0=
  access_key_id:
    secure: sI9vH3D9jEpHBe4K5aIh06V7lcD4goz5ZWndGkToxIrqCk1ffPWT8WBfyWEQvOlr1hBVm9NnnSynLP/uiGCD4VpCvLCfZZRsIIN9+MP8HY45rL7F4wnV4PbJmrxe2e/ZIhMx7n8PykfhvWenADi2eKTBkPk/ADgfbMzRgfl6ZCCbrdovKievmVLumaSXz45T5al5m5M3OvAutCVaBFGCzkyzKKFuiomBCs6nRovMyr5h2yO7yoRPBegm+YtIjCCcqZv4oGsqo7nQeEjfntmyBtDeJaJ6KT8HiJ2B9l9QY1H5TaQm/2J0MkKGXPwHokYEEaGjjJ2R8M1xQmEgJ/GkLbEyrZREeIWro8cxzgorP6GtDWPdV5krTu8nPCEBp1IzTlNwgmMAj4GJRegEQl8TDvhrOW1V7FuKm0dr9NjPlhAPIm8ihOejAQw43lIzsMNNC2ASu5+w/3PXR/Y1mDK0u3087QDGaQkYftb9nRD/U04sO1/enAz7Dh5ESvQcfgU+jcXhvKrptHqS2fXwc/F7Z3Xykl8tL6a0iWI5h9ht9qbEtF4hXTYIR+LQZl+JFQWd4hYccblmEMr+cprkA+liF37eFBcQTFmX7SmP3sZLei9KOB4j+TzIniJpKT5d5UxS65jBbYKgXcARtIlYbxAOKXlgFBfHZXl8lpt3WqLjGzU=
