language: python
python:
- '3.4'
branches:
  only:
  - horizon
  - master
env:
  global:
  - GH_REF: github.com/brownplt/pyret-docs.git
  - RACKET_DIR: "~/racket"
  - RACKET_VERSION: '6.5'
  - secure: tkOgKmY5brk6wSTluhgKaFiUiVVXnf1HefE1v56LOUlNHcieMLjRAgXc5LsdezI5ymtf59tZBVAdv7zWG+2Co/nMgIVE20FLpT2UeZCyBu+669lDPZG5zJcsq3Yp52EyE3pSzBRc5H5c9Ni3AZWunV/OxV8xUn3TMkTz9ian/j1AiyDK6z/s5TyFVuRITUOriyuE84e5HJvSYdCjMH2jZE3vCp+lBO9xK/+7IAyoXM7LBFIxz2qBbfzeGbDUzMiFujJZ0/cJu8Qfjlz/AEzW13BWhzhrI9FWUaawKJX1xU6gv9uhRgmsQqQjOMe2CdDuUiUoFP11WjbSnSsN7/B3oklqSiHNHFnOCbxYqunpEpI4EOltL0SpEFHZYl5JgtsLJTbqZvAJ0AaT88F8HBJEFthxyz6MhbBZ9CewOpFY50qY7yvsLr6JEEzCEnTk2EtIv6r2Ux5Xad+K2AXfpEPR1VvfRl6J4U7JGKHHspNVJmpdZSnJdYTzS2siHknV4LQ5Zrl1uwhTjTc4H6bshDKQfcXFkkc4edV78jrJiPDP5hpPVaqLH5MTLV0mhsrSowHPaOyL6y3y+/mrUFG7F0Lha9qdtT4k8PvD47ldPxBCaFOh85MC+w+p65WFqf2rwFMmZNA9sUTltFvU5OMtBPfTMpCrhgnBhf62UrLm6z2jJZY=
  - secure: LNFPDErTqBbgv3XgDI+X9q9Clb/BCFeuUcHjpzP5w5u4y2hpe3TnOkrLfI/FNNYqL2wczqA9cyQ6tDsczFatxz936heSU087uimPCEHKYuUk4jCZ3vM1iIH+MeiAEnaSDXmHOS0iSxvX86BU5AYULlRdpCNqU/12dzJZdARYhIGX+7LNUCUf2/D9MAbL85OjGjzR6ZEaJ5TdvL7IPKejsABiyU/TEAD6PNIgPaL4MRv+gqhedOak7nhFHUfJFUOVQ/GFE9np46HWW19aGIJSktO7RRCsDESUBte19qdQz+pABgn/mR3zVYsn0x7bd9VhpGHt5yeEpAhm82GB5MdkLVYCap8SgGHzl6IAXyToBTmC6wDxOQ/ivpWnkDum1W2rEuY/HrT1235Z7ea5YZVajg5uxAcnkpYqkOyWrLMm7yjXY6wdNQ9F1YKyx6GOxpZj/5opib3aF0hxIRF5nHD2ROZVgLeBM6PKliES1/X5GutBQCh3PsXwGd1G40YtUPXghMwxjYiDmwkM05fOnrUqwfobz98yrDm/6Q7KUEqUaUcV/RshLYcgXrOgSv9YSDykJ7BkvFhnDTOiHPVc4gg4GFHjZI0T8cCziyeroo3/pfR/Oe1kIXyuCzpP4kbY48JGE7GEvC7vT/dwOQ4ERt4XfzD2jlBaubqI6Boy95+VrKo=
before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash
- export PATH="${RACKET_DIR}/bin:${PATH}"
script:
  - npm install
  - make
deploy:
  provider: s3
  bucket: "pyret-docs"
  local_dir: build
  upload-dir: docs/horizon
  skip_cleanup: true
  access_key_id:
    secure: RWAyQY4NQC55Sjqh0hZq0V9LNlIaaFLDeoW7F0psLFz6t0LVjLLnY319mPkdKJqiQ/zSd78LO4FqHJi6bYGXs0Tx193DWRk0GtbCgttzTIpTOXhyN0ujjGTfu1ysG2mSPOhJxmxWDStGEGi5PShaeUHHskVty6Cq6a3xZfzxzs/HmfFbWY5TprbrdPgH/64r+kv6kOi4IBlpo30PzYE+bRVdseGkaGloiXOeWUvT8kBzq7vOvn6Ijo1HxvtSv86J3VzhareXKi9oczoQHbqHxB+symanv3S4mvu+kGfb3FLBXsQKBBtFCEQsm6MNupHKg+S5A9eBTp1rF6Po7fxq08LrTKpvkvFSLvtGujI+jHeoLXF72Uxh4L1antcKzQYbKNmcJF2s5BJ4puxnDo2TOY+O8aUWYnPWNDj3Zp/WvROv7CMkzJc5ZG503FCHcKYuvL9zT662FtuD5j2pxXMtR9dFxodMzK7tjdUsv89kKMTgpwdcXphz0Fn8Ujpgr0F7CYrI5BDdk5weGkXTtnwh8AIM31Smynd6pEvD1eT/gaYoac+g0QujpyHGKfyEWyveuqJ9UbLOUzn9K6+PNPgQbJc9WRUPfYeqqOgO2JsTJypUbtJVe/TxZY/mpTtfSOSyVaH6HW3aVEL7emIp7hatjP9i8AxTUgbl8WnfhX0uHqs=
  secret_access_key:
    secure: Gzgb+T8zETP6QW0NH5Ie6tRlmDxo2iYpQdHfd3v5HP79IeQU2p+Fm5xMxZDfw4kLhRNR/oB8dwTb+evy/GBs8ePIswFoT/Id5fbdFoQbkmA9k8TRjXV9zrxX+OCm8WpuMCtJMHvYRMDgD29YXBgGjEiukNuYXQPJ8mqmiODN2fEeFb0F2HuVWP4gGU7npEVxlWmc7bkq4cE+P37gjbhnae+QinKEKpwa2qf9vjCCb994Y5bZMLeLgtAYiLkztlSBOKaEOuXePocyeXDUU5LZQtg/HEgWyZSccZ/7TiQZGCHyLYs8/IyxVbcmuNHB9HorFwgUEluzEwUuJrVwws0sXBwyODkLJTenBS40B05Qmaa2M9fIjZLVsbeARke4HcjqTr1EIlAFOG/ZjD9x8VN/zPkvkWblLbmgMtjcg9ETKMesmJDyr/JJfm4G+4Oij32tzjo3+ZasvQrFA/2V5U873x6QRUREEKeJ5VPhSeJvD0ah3B4OQNgJtOXyGajLSEU/WLX2U8GTEjcNvcr/MGS8FpERdTsIuW3dbvEcBdkI3mX4nHL7w2OxGpngj6Syvs6DCJxCaeWRgZ3N54tZtqC9rOhwoJ8/v/r8jpKtPrV1LEc/Wvhm18Xa3ztwWOzBMJdcr734hmgjfDaaxfTbMn8m1QYNwmE1UHEunNFL1zt4P5U=
